/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["root__get"];
  };
  "/{item_id}": {
    get: operations["item__item_id__get"];
  };
}

export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Item */
    Item: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Description */
      description?: string;
      /** Price */
      price: number;
      /** Tax */
      tax?: number;
      /**
       * Tags
       * @default
       */
      tags?: string[];
    };
    /** ItemList */
    ItemList: {
      /** Items */
      items: number[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (Partial<string> & Partial<number>)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
}

export interface operations {
  root__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ItemList"];
        };
      };
    };
  };
  item__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Item"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}

export interface external {}
