/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["root__get"];
  };
}

export interface components {
  schemas: {
    /** Item */
    Item: {
      /** Name */
      name: string;
      /** Description */
      description?: string;
      /** Price */
      price: number;
      /** Tax */
      tax?: number;
      /**
       * Tags
       * @default
       */
      tags?: string[];
    };
  };
}

export interface operations {
  root__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Item"];
        };
      };
    };
  };
}

export interface external {}
